import {useState} from "react";
import {labels,type Equipment,type Bonus} from "./shop-model";
import {preciseTime,rankLaps,periodStart,type Lap,type Period} from "./leaderboard-model";
export function Leaderboard({laps,gen,equipment,mode,tier,bonus,onClose,onPublic}:{laps:Lap[];gen:number;equipment:Equipment;mode:"training"|"free";tier:number;bonus:Bonus;onClose:()=>void;onPublic?:()=>void}){
 const [generation,setGeneration]=useState(gen),[gear,setGear]=useState(equipment),[raceMode,setRaceMode]=useState(mode),[period,setPeriod]=useState<Period>("session"),[selectedTier,setTier]=useState(tier),[selectedBonus,setBonus]=useState(bonus);
 const filtered=laps.filter(l=>l.gen===generation&&l.equipment===gear&&l.mode===raceMode&&l.finishedAt>=periodStart(period,Date.now())&&(raceMode==="training"||(l.tier===selectedTier&&l.bonus===selectedBonus)));
 const ranked=rankLaps(filtered),leader=ranked[0];
 const history=[...filtered].sort((a,b)=>b.id-a.id).slice(0,10);
 return <div className="leaderboard-panel" role="dialog" aria-label="Tableau des chronos"><header className="picker-heading"><div><small>SPARKING STARS · TABLEAU DES CHRONOS</small><h2>La chasse au top 1</h2></div><button onClick={onClose}>Retour au circuit</button></header>
 {onPublic&&<button onClick={onPublic}>Voir le classement public ↗</button>}
 <p className="board-notice">Classement de cette session uniquement · chronos non vérifiés par un serveur. Aucun classement mondial ni récompense compétitive. Recharger efface ces résultats.</p>
 <div className="board-filters"><label>Terrain<select aria-label="Terrain" value={generation} onChange={e=>setGeneration(Number(e.target.value))}>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>GEN {g}</option>)}</select></label><label>Catégorie<select aria-label="Catégorie" value={gear} onChange={e=>setGear(e.target.value as Equipment)}>{(["feet","rollers","kart"] as Equipment[]).map(e=><option key={e} value={e}>{labels[e]}</option>)}</select></label><label>Mode<select aria-label="Mode" value={raceMode} onChange={e=>setRaceMode(e.target.value as "training"|"free")}><option value="training">Entraînement</option><option value="free">Course libre</option></select></label><label>Période (UTC)<select aria-label="Période (UTC)" value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="session">Toute la session</option><option value="day">Aujourd’hui</option><option value="week">Cette semaine</option><option value="month">Ce mois</option></select></label>
 {raceMode==="free"&&<><label>Tier officiel<select aria-label="Tier officiel" value={selectedTier} onChange={e=>setTier(Number(e.target.value))}>{[0,1,2,3,4].map(t=><option key={t} value={t}>Tier {t}</option>)}</select></label><label>Bonus équipé<select aria-label="Bonus équipé" value={selectedBonus} onChange={e=>setBonus(e.target.value as Bonus)}>{(["none","boost","breaker"] as Bonus[]).map(b=><option key={b} value={b}>{labels[b]}</option>)}</select></label></>}</div>
 <div className="leader-banner"><span>✦ TEMPS DE RÉFÉRENCE · TOP 1 DE SESSION</span><strong data-testid="leader-time">{leader?preciseTime(leader.ms):"À toi d’ouvrir la piste"}</strong><small>{leader?`Friend #${leader.friendId} · GEN ${generation} · ${labels[gear]}`:"Termine un tour dans cette catégorie pour inscrire un chrono."}</small></div>
 <p className="board-rules">Meilleur tour par Friend. Temps identiques : ex æquo. {raceMode==="training"?"Toutes les étoiles, sans consommable.":"Même tier et même bonus équipé pour comparer les courses libres."}</p>
 {ranked.length?<div className="board-table-wrap"><table><caption>Classement de la catégorie</caption><thead><tr><th>Rang</th><th>Pilote</th><th>Temps</th><th>Écart au top 1</th></tr></thead><tbody>{ranked.map(l=><tr key={l.friendId}><td>#{l.rank}</td><td>Friend #{l.friendId}</td><td>{preciseTime(l.ms)}</td><td>{l.gap===0?"Référence":"+"+preciseTime(l.gap)}</td></tr>)}</tbody></table></div>:<div className="board-empty">Pas encore de tour terminé dans cette catégorie.</div>}
 <h3>Les derniers tours</h3><p className="board-rules">Dix derniers tours de la catégorie · {filtered.length} tour{filtered.length!==1?"s":""} terminé{filtered.length!==1?"s":""} pendant cette session.</p><ol className="lap-history">{history.map(l=><li key={l.id}><span>Tour {l.id} · Friend #{l.friendId}</span><strong>{preciseTime(l.ms)}</strong><small>{leader&&l.ms===leader.ms?"Temps de référence":"+"+preciseTime(l.ms-(leader?.ms??l.ms))}</small></li>)}</ol>
 </div>;
}
