import {useEffect,useRef,useState} from 'react';
export function stickDirection(x:number,y:number){const length=Math.hypot(x,y);if(length<14)return {x:0,y:0};const angle=Math.atan2(y,x),sector=Math.round(angle/(Math.PI/4));return {x:Math.round(Math.cos(sector*Math.PI/4)),y:Math.round(Math.sin(sector*Math.PI/4))};}
export function TouchStick({onDirection,onControl}:{onDirection:(x:number,y:number)=>void;onControl:(kind:'touch'|'mouse'|'pen')=>void}){
 const pointer=useRef<number|null>(null),[knob,setKnob]=useState({x:0,y:0});
 const release=()=>{pointer.current=null;setKnob({x:0,y:0});onDirection(0,0);};
 useEffect(()=>{const stop=()=>release();window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);return()=>{window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);onDirection(0,0);};},[]);
 const update=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,length=Math.hypot(x,y),scale=length>40?40/length:1;setKnob({x:x*scale,y:y*scale});const direction=stickDirection(x,y);onDirection(direction.x,direction.y);};
 return <div className="touch-stick" role="group" aria-label="Joystick tactile" data-testid="touch-stick" onPointerDown={e=>{if(pointer.current!==null)return;e.preventDefault();pointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);onControl(e.pointerType==='touch'?'touch':e.pointerType==='pen'?'pen':'mouse');update(e);}} onPointerMove={e=>{if(pointer.current===e.pointerId){e.preventDefault();update(e);}}} onPointerUp={e=>{if(pointer.current===e.pointerId)release();}} onPointerCancel={e=>{if(pointer.current===e.pointerId)release();}} onLostPointerCapture={e=>{if(pointer.current===e.pointerId)release();}}><span className="stick-guide" aria-hidden="true">✦</span><span className="stick-knob" style={{transform:`translate(${knob.x}px,${knob.y}px)`}} aria-hidden="true"/><small>Pouce gauche</small></div>;
}
