import assert from 'node:assert/strict';
import {build} from 'esbuild';
const compile=async file=>{const r=await build({entryPoints:[file],bundle:true,platform:'node',format:'esm',write:false});return import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));};
const {emptyQuests,completeQuest}=await compile('games/sparking-stars/quests.ts');
const {questStore}=await compile('host/quest-store.ts');
const ghost=ms=>({ms,points:[[0,100,100],[ms,110,110]]});
let state=emptyQuests();for(const [i,ms]of [10000,14000,12000,11000,13000].entries())state=completeQuest(state,ghost(ms),String(i)).state;
assert.equal(state.target.ms,12000);assert.equal(state.laps,5);assert.equal(state.beaten,false);
state=completeQuest(state,ghost(20000),'slow').state;assert.equal(state.target.ms,12000);assert.equal(state.near,0);
state=completeQuest(state,ghost(12360),'near1').state;assert.equal(state.near,1);
state=completeQuest(state,ghost(18000),'slow2').state;assert.equal(state.near,1);
state=completeQuest(state,ghost(12100),'near2').state;const result=completeQuest(state,ghost(12000),'near3');assert.equal(result.state.wins,1);assert.equal(result.state.target.ms,12360);assert(result.earned.includes('Défi du fantôme réussi'));
assert.deepEqual(completeQuest(result.state,ghost(12000),'near3').earned,[]);assert.equal(completeQuest(result.state,ghost(12000),'near3').state.laps,result.state.laps);
const fast=completeQuest(result.state,ghost(9000),'record');assert(fast.state.beaten);assert(fast.earned.includes('Chasseur de fantômes'));assert.equal(fast.state.wins,2);
const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};
let store=questStore(storage,'0xABC','123','rules');store.complete(1,'training','feet','touch',ghost(10000),'a');
assert.equal(questStore(storage,'0xabc','123','rules').read()['123:1:training:feet:rules:touch'].laps,1);
assert.deepEqual(questStore(storage,'0xabc','124','rules').read(),{});assert.deepEqual(questStore(storage,'0xabc','123','newrules').read(),{});assert.deepEqual(questStore(storage,'0xdef','123','rules').read(),{});
store.complete(1,'training','feet','desktop',ghost(9000),'b');assert.equal(store.read()['123:1:training:feet:rules:touch'].laps,1);assert.equal(store.read()['123:1:training:feet:rules:desktop'].laps,1);
assert.throws(()=>store.complete(1,'free','feet','touch',ghost(10000),'c'));assert.throws(()=>store.complete(1,'training','feet','touch',{ms:10000,points:[[0,-1,0],[10000,10,10]]},'c'));
const blocked={getItem:()=>null,setItem:()=>{throw Error('blocked');}};assert.equal(questStore(blocked,'0xblocked','123','rules').complete(1,'training','feet','touch',ghost(10000),'x').saved,false);assert.equal(questStore(blocked,'0xblocked','123','rules').complete(1,'training','feet','touch',ghost(11000),'y').state.laps,2);
console.log('PASS quests: fixed median target, 3% nonconsecutive consistency, renewal, permanent badges, idempotency, category/identity isolation, persistence and blocked-storage fallback.');
